### ISSUE TITLE
Doctrine2 Support?

### ISSUE THREAD

**Issue by Bup3** [opichon/UAMDatatablesBundle#2]
Is it possible to use this with Doctrine2?

I installed you bundle and tried to set it up but i've got a few errors because you're using Propel things which are incompatible with Doctrine.

I try to overwrite your trails now.

**Comment by opichon** [comment]
The bundle has been designed to be ORM-agnostic, but the only concrete implementation provided at this stage is for Propel ORM. I am fairly confident that a doctrine implementation is feasible. All that should be required is to create an EntityManager implementation that uses Doctrine. I am afraid that I don't have the resources right now for this, but if you want to provide a PR, I'd be happy to review it.

**Comment by Bup3** [comment]
Ok thanks. I try to create one.
